export const FRIEND_lIST_REQUEST = 'FRIEND_lIST_REQUEST';
export const FRIEND_LIST_SUCESS = 'FRIEND_LIST_SUCESS';
export const FRIEND_LIST_FAILURE = 'FRIEND_LIST_FAILURE';

export const FRIEND_MESSAGE_REQUEST = 'constFRIEND_MESSAGE_REQUEST';
export const FRIEND_MESSAGE_SUCESS = 'constFRIEND_MESSAGE_SUCESS';
export const FRIEND_MESSAGE_FAILURE = 'constFRIEND_MESSAGE_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCESS = 'SEND_MESSAGE_SUCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';