export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCESS = 'REGISTER_SUCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CHECK_REQUEST = 'CHECK_REQUEST';
export const NOT_REPEAT = 'NOT_REPEAT';
export const NAME_REPEAT = 'NAME_REPEAT';
export const CHECK_FAILURE = 'CHECK_FAILURE';