export const GET_USER_INFO_REQEUST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCESS = 'GET_USER_INFO_SUCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCESS = 'UPDATE_USER_INFO_SUCESS';
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE';